[package]
name = "dpll_cli"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "dpll"
path = "src/bin/dpll.rs"

[[bin]]
name = "min"
path = "src/bin/min.rs"

[dependencies]
dpll_core = { path = "../core" }         # core DPLL solver logic
dpll_parallel = { path = "../parallel" } # parallel DPLL logic

log = { workspace = true }
nonzero_ext = { workspace = true }

clap = { version = "4.5.53", features = ["derive"] } # CLI arg parsing
memmap2 = "0.9.9" # read problem files
env_logger = "0.11.8" # init logging from env vars
indicatif = { version = "0.18.3", features = [
    "improved_unicode",
] } # progress bars
indicatif-log-bridge = "0.2.3" # combine progress bars with logging
