[package]
name = "dpll_parallel"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[features]
default = []
metrics = []

[dependencies]
dpll_core = { path = "../core" }   # core DPLL solver logic
nonzero_ext = { workspace = true }

log = { workspace = true }

crossbeam-channel = "0.5.15"
crossbeam-deque = "0.8.6"
crossbeam-utils = "0.8.21"

[dev-dependencies]
fastrand = { workspace = true }
